#!/bin/bash

DOCKER_COMPOSE_FILE_NAME="docker-compose.yml"

PROMETHEUS_FOLDER="prometheus"
GRAFANA_FOLDER="grafana"
METRICS_FOLDER="metrics"

# Dashboarding
DASBOARDING_FOLDER="dashboarding"

export GRAFANA="$DASBOARDING_FOLDER/$GRAFANA_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

# Metrics
OBSERVER_FOLDER="observer"
CLUSTER_01="cluster-01"
CLUSTER_02="cluster-02"

export PROMETHEUS_C1_R1="$METRICS_FOLDER/$CLUSTER_01/$PROMETHEUS_FOLDER/r1/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C1_R2="$METRICS_FOLDER/$CLUSTER_01/$PROMETHEUS_FOLDER/r2/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C1_OBJ_STORAGE="$METRICS_FOLDER/$CLUSTER_01/thanos-object-store/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C1_COMPACTOR="$METRICS_FOLDER/$CLUSTER_01/thanos-compactor/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C1_QUERIER="$METRICS_FOLDER/$CLUSTER_01/thanos-querier/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C1_STORE="$METRICS_FOLDER/$CLUSTER_01/thanos-store/$DOCKER_COMPOSE_FILE_NAME"

export PROMETHEUS_C2_R1="$METRICS_FOLDER/$CLUSTER_02/$PROMETHEUS_FOLDER/r1/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C2_R2="$METRICS_FOLDER/$CLUSTER_02/$PROMETHEUS_FOLDER/r2/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C2_OBJ_STORAGE="$METRICS_FOLDER/$CLUSTER_02/thanos-object-store/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C2_COMPACTOR="$METRICS_FOLDER/$CLUSTER_02/thanos-compactor/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C2_QUERIER="$METRICS_FOLDER/$CLUSTER_02/thanos-querier/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_C2_STORE="$METRICS_FOLDER/$CLUSTER_02/thanos-store/$DOCKER_COMPOSE_FILE_NAME"

export PROMETHEUS_OBSERVER_ALERTMANAGER="$METRICS_FOLDER/$OBSERVER_FOLDER/alertmanager/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_OBSERVER_QUERIER="$METRICS_FOLDER/$OBSERVER_FOLDER/thanos-querier/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_OBSERVER_C1_RULER="$METRICS_FOLDER/$OBSERVER_FOLDER/thanos-ruler/$CLUSTER_01/$DOCKER_COMPOSE_FILE_NAME"
export PROMETHEUS_OBSERVER_C2_RULER="$METRICS_FOLDER/$OBSERVER_FOLDER/thanos-ruler/$CLUSTER_02/$DOCKER_COMPOSE_FILE_NAME"

# Self Monitoring
SELF_MONITORING_FOLDER="self-monitoring"
HOST_METRICS_FOLDER="host-metrics"

export SELF_GRAFANA="$SELF_MONITORING_FOLDER/$DASBOARDING_FOLDER/$GRAFANA_FOLDER/$DOCKER_COMPOSE_FILE_NAME"
export SELF_PROMETHEUS="$SELF_MONITORING_FOLDER/$METRICS_FOLDER/$PROMETHEUS_FOLDER/$DOCKER_COMPOSE_FILE_NAME"
export SELF_HOST_METRICS="$SELF_MONITORING_FOLDER/$METRICS_FOLDER/$HOST_METRICS_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

export ALL_COMPOSE_FILES=" -f "$GRAFANA\
" -f "$PROMETHEUS_C1_R1\
" -f "$PROMETHEUS_C1_R2\
" -f "$PROMETHEUS_C1_OBJ_STORAGE\
" -f "$PROMETHEUS_C1_COMPACTOR\
" -f "$PROMETHEUS_C1_QUERIER\
" -f "$PROMETHEUS_C1_STORE\
" -f "$PROMETHEUS_C2_R1\
" -f "$PROMETHEUS_C2_R2\
" -f "$PROMETHEUS_C2_OBJ_STORAGE\
" -f "$PROMETHEUS_C2_COMPACTOR\
" -f "$PROMETHEUS_C2_QUERIER\
" -f "$PROMETHEUS_C2_STORE\
" -f "$PROMETHEUS_OBSERVER_ALERTMANAGER\
" -f "$PROMETHEUS_OBSERVER_QUERIER\
" -f "$PROMETHEUS_OBSERVER_C1_RULER\
" -f "$PROMETHEUS_OBSERVER_C2_RULER\
" -f "$SELF_GRAFANA\
" -f "$SELF_PROMETHEUS\
" -f "$SELF_HOST_METRICS\
